kustomize:
  images:
  - pitacd/makeline-service:45
  - pitacd/order-service:45
  - pitacd/product-service:44
  - pitacd/store-admin:45
  - pitacd/store-front:45
  - grupo5sd/virtual_client:app-151
  - pitacd/virtual-worker:45
