kustomize:
  images:
  - pitacd/makeline-service:latest
  - pitacd/order-service:latest
  - pitacd/product-service:latest
  - pitacd/store-admin:latest
  - pitacd/store-front:latest
  - grupo5sd/virtual_client:latest
  - pitacd/virtual-worker:29
