name: Docker Build Images

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-folders: ${{ steps.extract-folders.outputs.changed-folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changes
        uses: tj-actions/changed-files@v37
        with:
          files: |
            src/makeline-service/**
            src/order-service/**
            src/product-service/**
            src/store-admin/**
            src/store-front/**
            src/virtual-worker/**

      - name: Extract Changed Folders
        id: extract-folders
        run: |
          echo "Changed folders: $(echo '${{ steps.changes.outputs.all_changed_files }}' | grep -o 'src/[^/]*/' | uniq | sed 's|src/||; s|/||')"
          echo "changed-folders=$(echo '${{ steps.changes.outputs.all_changed_files }}' | grep -o 'src/[^/]*/' | uniq | sed 's|src/||; s|/||')" >> $GITHUB_OUTPUT

  build-and-push:
    needs: determine-changes
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.determine-changes.outputs.changed-folders) != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.determine-changes.outputs.changed-folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Images
        uses: docker/build-push-action@v6
        with:
          context: src/${{ matrix.folder }}
          file: src/${{ matrix.folder }}/Dockerfile
          push: true
          tags: |
            pitacd/${{ matrix.folder }}:latest
            pitacd/${{ matrix.folder }}:${{ github.run_number }}
