name: Docker Build Images

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  publish-container-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [
          makeline-service,
          order-service,
          product-service,
          store-admin,
          store-front,
          virtual-worker
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changes
        uses: tj-actions/changed-files@v37
        with:
          files: |
            src/makeline-service/**
            src/order-service/**
            src/product-service/**
            src/store-admin/**
            src/store-front/**
            src/virtual-worker/**
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Images
        if: ${{ contains(steps.changes.outputs.all_changed_files, format('src/{0}/', matrix.app)) }}
        uses: docker/build-push-action@v6
        with:
          context: src/${{ matrix.app }}
          file: src/${{ matrix.app }}/Dockerfile
          push: true
          tags: |
            pitacd/${{ matrix.app }}:latest
            pitacd/${{ matrix.app }}:${{ github.run_number }}