name: Docker Build Images

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  publish-container-image:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        apps: [
          makeline-service,
          order-service,
          product-service,
          store-admin,
          store-front,
          virtual-customer,
          virtual-worker
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: src/${{ matrix.apps }}
          file: src/${{ matrix.apps }}/Dockerfile
          push: true
          tags: pitacd/${{ matrix.apps }}:${{ github.run_number }}

  modify-git:
    needs: publish-container-image
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        apps: [
          makeline-service,
          order-service,
          product-service,
          store-admin,
          store-front,
          virtual-customer,
          virtual-worker
        ]
        
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        name: Changing the deployments of git repo
        with:
          repository: 'LeJoneMacarone/aks-store-demo'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Modify the image
        run: |
          git config user.email ${{ secrets.USER_EMAIL }}
          git config user.name LeJoneMacarone
          pwd
          cat kustomize/base/${{ matrix.apps }}.yaml
          pwd
          sed -i "s+image: pitacd/${{ matrix.apps }}:.*+image: pitacd/${{ matrix.apps }}:${{ github.run_number }}+g" kustomize/base/${{ matrix.apps }}.yaml
          cat kustomize/base/${{ matrix.apps }}.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job change manifest: ${{ github.run_number }}'
          git push origin main