name: Docker Build Images

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  publish-container-image:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        apps: [
          makeline-service,
          order-service,
          product-service,
          store-admin,
          store-front,
          virtual-worker
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: src/${{ matrix.apps }}
          file: src/${{ matrix.apps }}/Dockerfile
          push: true
          tags: |
            pitacd/${{ matrix.apps }}:latest
            pitacd/${{ matrix.apps }}:${{ github.run_number }}
