name: Docker Build Images

on:
  push:
    branch:
      - "main"
      - "release"

permissions:
  contents: read
  packages: write

jobs:
  publish-container-image:
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        apps: [
          makeline-service,
          order-service,
          product-service,
          store-admin,
          store-front,
          virtual-customer,
          virtual-worker
        ]

    steps:
      - name: Set environment variables
        id: set-variables
        run: |
          echo "IMAGE=${{ matrix.apps }}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${{github.run_number}}" >> "$GITHUB_OUTPUT"
          echo "CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
      
      - name: Environment variables output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.IMAGE }}
          echo ${{ steps.set-variables.outputs.VERSION }}
          echo ${{ steps.set-variables.outputs.CREATED }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: src/${{ matrix.apps }}
          file: src/${{ matrix.apps }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ steps.set-variables.outputs.VERSION }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.set-variables.outputs.IMAGE }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.set-variables.outputs.IMAGE }}:${{ steps.set-variables.outputs.VERSION }}
          labels: |
            org.opencontainers.image.created=${{ steps.set-variables.outputs.CREATED }}
            org.opencontainers.image.revision=${{ steps.set-variables.outputs.VERSION }}
          